import { NextRequest, NextResponse } from "next/server";
import { generateDocument, type DocType } from "@/lib/documentGenerator";
import { createHash, randomUUID } from "crypto";
import { recordUsage } from "@/lib/recordUsage";

// Use globalThis to share the file store across route modules
function getFileStore() {
  if (!(globalThis as any).__niaFileStore) {
    (globalThis as any).__niaFileStore = new Map();
  }
  return (globalThis as any).__niaFileStore as Map<string, {
    buffer: Buffer;
    filename: string;
    mimeType: string;
    type: DocType;
    size_bytes: number;
    pages: number;
    created_at: string;
    content_hash: string;
    request_message_id?: string;
  }>;
}

export async function POST(req: NextRequest) {
  let type = "", request_message_id = "", chat_id = "";
  try {
    const body = await req.json();
    type = body.type;
    request_message_id = body.message_id || "";
    chat_id = body.chat_id || "";
    const { title, subtitle, content_markdown, options, target_pages, strict_pages } = body;

    if (!type || !title || !content_markdown) {
      return NextResponse.json({ error: "Missing required fields: type, title, content_markdown" }, { status: 400 });
    }

    const validTypes: DocType[] = ["pdf", "docx", "xlsx", "csv", "pptx", "md"];
    if (!validTypes.includes(type as DocType)) {
      return NextResponse.json({ error: `Invalid type. Must be one of: ${validTypes.join(", ")}` }, { status: 400 });
    }

    const mergedOptions = { ...options, subtitle, target_pages: target_pages ?? undefined, strict_pages: strict_pages ?? undefined };

    console.log(`[doc-gen] target_pages=${target_pages ?? "none"} type=${type} title="${title}"`);

    const result = await generateDocument(type as DocType, title, content_markdown, mergedOptions);

    // Post-render validation: for PDFs, verify the page count using the buffer size
    // and detect potential blank pages (the buffer is already generated by PDFKit with accurate count)
    const actualPages = result.pages;

    // Compute content hash to uniquely identify this document's content
    const content_hash = createHash("sha256")
      .update(title + content_markdown)
      .digest("hex");

    // Generate a proper UUID for the file ID
    const fileId = randomUUID();

    // Log generation job details for debugging and traceability
    console.log(`[doc-gen]`, JSON.stringify({
      file_id: fileId,
      title,
      content_hash,
      pages: actualPages,
      size_bytes: result.size_bytes,
    }));

    const fileStore = getFileStore();

    // Store in the global in-memory store
    fileStore.set(fileId, {
      buffer: result.buffer,
      filename: result.filename,
      mimeType: result.mimeType,
      type: result.type,
      size_bytes: result.size_bytes,
      pages: actualPages,
      created_at: new Date().toISOString(),
      content_hash,
      ...(request_message_id ? { request_message_id: String(request_message_id) } : {}),
    });

    // Record document generation usage
    recordUsage({
      chat_id: chat_id || "",
      message_id: request_message_id || "",
      kind: "tool_pdf",
      provider: "local",
      model: type,
      input_tokens: 0,
      output_tokens: 0,
      cost_usd: 0,
      latency_ms: 0,
    });

    return NextResponse.json({
      url: `/api/files/${fileId}`,
      filename: result.filename,
      type: result.type,
      size_bytes: result.size_bytes,
      pages: actualPages,
      file_id: fileId,
      target_pages: result.target_pages,
      fit_exact: result.fit_exact,
    });
  } catch (error) {
    console.error("Document generation error:", error);
    recordUsage({
      chat_id: chat_id || "",
      message_id: request_message_id || "",
      kind: "tool_pdf",
      provider: "local",
      model: type || "unknown",
      input_tokens: 0,
      output_tokens: 0,
      cost_usd: 0,
      latency_ms: 0,
      status: "error",
      error_message: error instanceof Error ? error.message : "Document generation failed",
    });
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Document generation failed" },
      { status: 500 }
    );
  }
}
